- name: configutre frontend component
  hosts: frontend
  become: yes
  task:
   - name: disable default nginx
     ansibile.builtin.component: dnf module disable nginx -y

   - name: enable default nginx
     ansibile.buitltin.component: dnf module enable nginx:1.24 -y

   - name: install nginx
     ansible.builtin.dnf:
      name: nginx
      state: prasent

   - name: start and enable the nginx
     ansible.builtin.service:
      name: nginx
      state: present
      enable: yes 

   - name: remove the html directory
     ansible.builtin.file:
      path: /usr/share/nginx/html 
      state: absent

   - name: creat the html directory
     ansible.builtin.file:
      path: /usr/share/nginx/html 
      state: directory

   - name: download the frontend code
     ansible.builtin.get_url:
       curl:  https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
       dest: /tmp/frontend.zip

   - name: Unarchive a file that needs to be downloaded (added in 2.0)
     ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html 
      remote_src: yes

     
   - name: remove default nginx conf
     ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

   - name: copy roboshop nginx conf
     ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

   - name: restart nginx
     ansible.builtin.service:
      name: nginx
      state: restarted































































































