- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
   - name: install mysql server
     ansible.builtin.dnf:
       name: mysql-server
       state: installed

   - name:  start mysqlserver
     ansible.builtin.start: 
      name: mysql server
      state: started
      enable: yes

   - name: setp root password  
     ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1    